### ISSUE TITLE
Nuxt module should be a function: vue-email/nuxt

### ISSUE THREAD

**Issue by designchapnl** [vue-email/nuxt#10]
I'm trying to run the latest vue-email (0.8.5) and the latest vue-email/nuxt plugin (0.8.7) with latest Nuxt (3.9.0), but I'm getting this error:  ERROR  Nuxt module should be a function: vue-email/nuxt. How can I fix this?

**Comment by v-moravec** [comment]
You should only install the `@vue-email/nuxt` dependency and then in Nuxt config file put `@vue-email/nuxt` into `modules`. Maybe you missed the `@`?

**Comment by designchapnl** [comment]
I feel very stupid. So I did miss the @. Thank you!

**Comment by Flowko** [comment]
@v-moravec thanks!

@designchapnl more info here https://vuemail.net/ssr/nuxt
