### ISSUE TITLE
Devtools in lightmode is almost unreadable

### ISSUE THREAD

**Issue by sduduzog** [vue-email/nuxt#15]
<img width="689" alt="image" src="https://github.com/vue-email/nuxt/assets/48126337/40c44fbf-8754-4a0f-9dd8-f6b258db6467">

I thought I had broken something but I realize the colors for text are just very faint

**Comment by sduduzog** [comment]
This is how the items I'm hovering over look like
<img width="1032" alt="image" src="https://github.com/vue-email/nuxt/assets/48126337/249eef7a-c325-4b50-8c62-db6120fcf3eb">

**Comment by Flowko** [comment]
yikes, thanks for the issue, will try to resolve this issue as soon as i can

**Comment by Flowko** [comment]
fixed in `0.8.9`
