### ISSUE TITLE
Email Template not found on production build

### ISSUE THREAD

**Issue by eBrou** [vue-email/nuxt#16]
HI - I posted a comment on the related issue: https://github.com/vue-email/nuxt/issues/13.  Creating a new issue just in case you don't get notified of comments on a closed issue.  

@Flowko Hi. First, thank you for your work on this module!

I'm looking into a similar issue (to https://github.com/vue-email/nuxt/issues/13) and it has not been solved by upgrading to 0.8.8, which was the proposed solution.
I'm also seeing that the stackblitz linked in that issue (https://stackblitz.com/edit/github-usvs6j-5oeyxy?file=package.json,emails%2Ftest.vue,nuxt.config.ts) still has the same error, even with the updated version. 
(If that link isn't adequate I can look into creating a separate stackblitz soon)

Could you please advise?
Thanks in advance

**Comment by Flowko** [comment]
Hi, thanks for opening another issue, tottally missed the other one, probabaly because its closed, tbh im not even sure whats causing it to break inside of stackblitz, locally it works fine with building as well, yould you be down to make a reproduction using vercel ?

**Comment by eBrou** [comment]
Hi, sorry for the delay, I've been out sick.
A member of my team was also looking into this and was able to solve it!
From him:  

> Our issue ended up being a corrupt lock file.  Our build version was missing esbuild-linux-64 which caused it to fail on deploy. 

Closing this issue now.  Thanks!
