### ISSUE TITLE
Cannot use custom components in Nuxt

### ISSUE THREAD

**Issue by Mokkapps** [vue-email/nuxt#20]
## Actual Behavior

I cannot use custom components in the `~/emails` folder, I get the following error

```
[Vue warn]: Failed to resolve component: EmailCustomLink
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

## Expected Behavior

It should work as described in https://github.com/vue-email/vue-email/issues/64

## Reproduction

https://stackblitz.com/edit/nuxt-starter-a69obu?file=emails%2FCustomLink.vue

**Comment by Flowko** [comment]
Hi, you just need to use the name of the component, without the `Email` prefix

![image](https://github.com/vue-email/nuxt/assets/35883748/9f0ff484-1dfb-4cb0-9642-94e2b5996070)

**Comment by Mokkapps** [comment]
Thanks, that works 👍🏻🚀
