### ISSUE TITLE
Nuxt Devtools not showing emails

### ISSUE THREAD

**Issue by mtrnik** [vue-email/nuxt#30]
Hello, I only see example dashboard when accessing Vue Email tab.

![Screenshot 2024-02-23 at 08 52 01](https://github.com/vue-email/vue-email/assets/12171220/9d1f8b93-ef79-422e-9861-77f63ad7dbcf)

And I see this error in the terminal:

![Screenshot 2024-02-23 at 08 50 51](https://github.com/vue-email/vue-email/assets/12171220/4aa100c5-d6bd-4172-89b1-0640999e2b16)

Is something wrong on my side or is there a bug in the code for fetching email components from directory?

Thank you for your help

**Comment by Flowko** [comment]
I'll take a look, thanks

**Comment by Flowko** [comment]
could you please provide a reproduction or at least show me what you have inside the `emails` folder

**Comment by mtrnik** [comment]
I can't share my real code, but it is empty even if I just use this template https://github.com/vue-email/docs/blob/main/components/content/emails/EmailTemplate.vue and put it into /emails/test.vue file

**Comment by Flowko** [comment]
try to update to the latest version of the package `^0.8.17` and check if the emails showing by clicking on search, i just tested with the same template using the latest version, seems to be working for me

**Comment by mtrnik** [comment]
@Flowko Thank you so much. It works without any problem now.
