### ISSUE TITLE
baseUrl not present after running export command

### ISSUE THREAD

**Issue by stursby** [vue-email/nuxt#41]
I have the following command to compile the `.vue` emails into `HTML`, however the `baseUrl` is gone after exporting.

Here's the relevant parts of each component

### Email

```vue
<EImg
  src="/images/logo.png"
  width="100"
  height="33"
  alt="logo"
  :style="logo"
/>
```

### Nuxt Config

```ts
// Email
vueEmail: {
  baseUrl: 'https://example.com'
}
```

### package.json

```json
{
  "scripts": {
    "email": "bunx vue-email export --dir emails --out supabase/templates --pretty"
  }
}

```

When previewing the Email w/ Nuxt Dev Tools, the Image URL works great:

<img width="477" alt="image" src="https://github.com/vue-email/nuxt/assets/527849/e1b2a580-5e34-44f3-9e5b-f5d029eb9b73">

However, after I run the build command, the `baseUrl` is omitted:

![image](https://github.com/vue-email/nuxt/assets/527849/85be342b-673c-48a7-83ce-2cfe7e94812c)

Any help would be much appreciated!!

PS -- What I eventually would like to do is set the `baseUrl` to an ENV variable to so it works both locally and in production!

```ts
// Email
vueEmail: {
  baseUrl: process.env.BASE_URL,
}
```

Thanks for the awesome library BTW! 💯

**Comment by Flowko** [comment]
we just merged a new project rewrite, please do check the docs and the updated logic https://vuemail.net/
