### ISSUE TITLE
useCompiler return type missing ?

### ISSUE THREAD

**Issue by lewebsimple** [vue-email/nuxt#43]
It seems `useCompiler` returns `Promise<any>` when used like so:
```
import { useCompiler } from "#vue-email";

export default defineEventHandler(async () => {
  const template = await useCompiler("TestEmail.vue");
  return template.html;
});
```

Am I missing something ?

**Comment by Flowko** [comment]
we just merged a new project rewrite, please do check the docs and the updated logic https://vuemail.net/
