### ISSUE TITLE
Provide Demos in the docs

### ISSUE THREAD

**Issue by esadrian** [vue-email/nuxt#44]
Hello, I've been trying to make this module send the templates unsuccessfully.

My setup is Nuxt 3 (SSR) and want to use with nodemailer (but could work with any other really). After reading articles, documentation back and forth and attempting tons of tries, everything seems misleading.

There is nothing that would help most than a **minimal demo page** like they do with other modules. 
See https://tailwindcss.nuxtjs.org/examples/basic for reference.

The basic stuff should cover form _inputs_ that add info to _props_, that are included in the email _template_, that is _sent_ with the desired provider (nodemailer or else).

Do you think this is possible? Would help a lot. Thanks!

**Comment by BoldSalt** [comment]
This would be very helpful. I'm almost at the point of giving up on this and finding an alternative to use as vue-email seems to be abandoned.

**Comment by Flowko** [comment]
we just merged a new project rewrite, please do check the docs and the updated logic https://vuemail.net/
