### ISSUE TITLE
useCompiler memory leak

### ISSUE THREAD

**Issue by mtrnik** [vue-email/nuxt#46]
Hello, I'm facing weird issue with the memory consumption on prod server which is constantly growing and never freed up. I have track it down to the useComplier method. Every time this method is called the used heap memory increases and almost never decreases back to previous value. 

I prepared sample repo [https://github.com/mtrnik/nuxt-email/tree/main/sample](https://github.com/mtrnik/nuxt-email/tree/main/sample) with very basic example of usage. 

And also few screenshots from which show the issue

![Screenshot 2024-05-28 at 16 23 55](https://github.com/vue-email/nuxt/assets/12171220/8df0f256-c10f-44bb-bdc6-cbba1fbc4758)
![Screenshot 2024-05-28 at 16 23 30](https://github.com/vue-email/nuxt/assets/12171220/99acb7dd-4148-4dfd-9c8a-4e8b69032b7b)
![Screenshot 2024-05-28 at 16 23 11](https://github.com/vue-email/nuxt/assets/12171220/f87ba90f-4a88-4c39-82b1-7c958f6cf6d8)
![Screenshot 2024-05-28 at 16 23 03](https://github.com/vue-email/nuxt/assets/12171220/fd782677-222a-45ed-99ed-901fba4e2171)

**Comment by Flowko** [comment]
we just merged a new project rewrite, please do check the docs and the updated logic https://vuemail.net/
