### ISSUE TITLE
Incorrect behavior when 'srcDir' is set (Nuxt3)

### ISSUE THREAD

**Issue by Prochy20** [vue-email/nuxt#48]
Hello,

when you set your `srcDir: '/src'` in `nuxt.config.ts` it breaks the implementation of this plugin:

Your emails must be still in the root project folder and so you cannot use its whole potential, as the composables, for instance, do not work there (since they are supposed to be at ./src)

**Reproductory steps** 

1. Install nuxt
2. add `srcDir: '/src'` to `nuxt.config.ts` (see https://nuxt.com/docs/api/nuxt-config#srcdir)
3. add vue-email module

Can you check this?

Thanks,

Martin.

**Comment by Flowko** [comment]
we just merged a new project rewrite, please do check the docs and the updated logic https://vuemail.net/
