### ISSUE TITLE
[deno] The string to be encoded contains characters outside of the Latin1 range.

### ISSUE THREAD

**Issue by k2s** [vue-email/nuxt#50]
The problem exists when the email template contains non-Latin1 characters and is running under **Deno**.

This seems to be related to https://github.com/vue-email/compiler/pull/8. 
I tried it also with @vue-email/nuxt-edge@latest.

I see the compiler will be abandoned.  Could you, please, make sure that this type of template will work in https://github.com/vue-email/nuxt/pull/47 ?

My replicable code is based on Nuxt https://github.com/k2s/nuxt-vue-email-problem.

- run my repo with `npm run problem`
- visit http://localhost:3000/api/ok - it will work
- visit http://localhost:3000/api/bad - it will fail

**Comment by Flowko** [comment]
we just merged a new project rewrite, please do check the docs and the updated logic https://vuemail.net/
